/**  -------------------------------------------------- */
/**  Generated by Enterprise Architect Version 11.0.1106*/
/**  Created On : 星期二, 14 四月, 2015 */
/**  DBMS       : MySql */
/**  -------------------------------------------------- */

USE TestDb
;
DROP TABLE IF EXISTS 文章 CASCADE
;
CREATE TABLE 文章
(
	ID CHAR(10) NOT NULL,
	Name CHAR(10) NOT NULL,
	ID CHAR(10) NOT NULL,
	Upload time DATE NOT NULL,
	PRIMARY KEY (ID, Name)

) 
;


