/**  -------------------------------------------------- */
/**  Generated by Enterprise Architect Version 11.0.1106*/
/**  Created On : 星期二, 14 四月, 2015 */
/**  DBMS       : MySql */
/**  -------------------------------------------------- */

USE TestDb
;
DROP TABLE IF EXISTS 编辑 CASCADE
;
CREATE TABLE 编辑
(
	ID CHAR(10) NOT NULL,
	PRIMARY KEY (ID)

) 
;


