/**  -------------------------------------------------- */
/**  Generated by Enterprise Architect Version 11.0.1106*/
/**  Created On : 星期二, 14 四月, 2015 */
/**  DBMS       : MySql */
/**  -------------------------------------------------- */

USE TestDb
;
DROP TABLE IF EXISTS Publish CASCADE
;
CREATE TABLE Publish
(
	Name CHAR(10) NOT NULL,
	KEY (Name)

) 
;


ALTER TABLE Publish ADD CONSTRAINT FK_发布_文章 
	FOREIGN KEY (Name) REFERENCES 文章 (ID, Name)
;

